# Generated by Django 4.2.7 on 2024-01-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='등록날짜'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postname',
            field=models.CharField(max_length=50, verbose_name='제목'),
        ),
    ]
