# Generated by Django 4.2.7 on 2024-02-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_users_options_alter_users_username'),
        ('board', '0002_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_posts', to='user.users', verbose_name='글쓴이'),
        ),
    ]
