# Generated by Django 4.2.7 on 2024-02-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
