# Generated by Django 4.2.7 on 2024-01-17 14:40

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_post_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.upload_path, verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일'),
        ),
    ]
