# Generated by Django 4.2.7 on 2024-02-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_file_image_remove_post_photo_post_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
