# Generated by Django 4.2.7 on 2024-01-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_post_photo_alter_post_updated_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='비밀글 여부'),
        ),
    ]
