# Generated by Django 4.2.7 on 2024-03-06 03:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')], verbose_name='연락처')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('contents', models.TextField(max_length=3000, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_posts', to=settings.AUTH_USER_MODEL, verbose_name='글쓴이')),
            ],
            options={
                'verbose_name': '강의상담문의',
                'verbose_name_plural': '강의상담문의',
                'db_table': 'lecture',
            },
        ),
    ]
