# Generated by Django 4.2.7 on 2024-03-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lectureCalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('date', models.DateField(verbose_name='날짜')),
                ('start_time', models.TimeField(verbose_name='시작시간')),
                ('end_time', models.TimeField(verbose_name='종료시간')),
            ],
            options={
                'verbose_name': '강의일정',
                'verbose_name_plural': '강의일정',
                'db_table': 'lecture_calender',
            },
        ),
        migrations.AlterModelTable(
            name='inquiry',
            table='lecture_inquiry',
        ),
    ]
