# Generated by Django 4.2.7 on 2024-03-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_lecturecalender_alter_inquiry_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturecalender',
            name='title',
        ),
        migrations.AddField(
            model_name='lecturecalender',
            name='contents',
            field=models.CharField(default=231213, max_length=200, verbose_name='내용'),
            preserve_default=False,
        ),
    ]
