# Generated by Django 4.2.7 on 2024-03-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_alter_lecturecalender_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturecalender',
            name='allDay',
            field=models.BooleanField(default=False, verbose_name='종일'),
        ),
    ]
