# Generated by Django 4.2.7 on 2024-03-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_lecturecalender_allday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturecalender',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='lecturecalender',
            old_name='start_time',
            new_name='startTime',
        ),
    ]
