# Generated by Django 4.2.7 on 2024-03-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_lecturetitle_lecturelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturelist',
            name='content',
        ),
    ]
