# Generated by Django 4.2.7 on 2024-03-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0008_remove_lecturelist_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturetitle',
            name='contents',
            field=models.TextField(default=1, max_length=200, verbose_name='설명'),
            preserve_default=False,
        ),
    ]
