# Generated by Django 4.2.7 on 2024-03-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0009_lecturetitle_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturecalender',
            name='contents',
            field=models.CharField(max_length=50, verbose_name='내용'),
        ),
    ]
