# Generated by Django 4.2.7 on 2024-03-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0010_alter_lecturecalender_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='연락처'),
        ),
    ]
