# Generated by Django 4.2.7 on 2024-03-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0011_alter_inquiry_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturelist',
            name='contents',
            field=models.TextField(default=4, max_length=200, verbose_name='설명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturelist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lecture/list/img/', verbose_name='이미지'),
        ),
    ]
