# Generated by Django 4.2.7 on 2024-02-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_users_options_alter_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('contents', models.TextField(max_length=3000, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_inquiry_posts', to='user.users', verbose_name='글쓴이')),
            ],
            options={
                'verbose_name': '강의상담문의',
                'verbose_name_plural': '강의상담문의',
                'db_table': 'lecture_inquiry',
            },
        ),
    ]
