# Generated by Django 4.2.7 on 2024-02-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_users_options_alter_users_username'),
        ('lecture_inquiry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Inquiry',
        ),
    ]
