# Generated by Django 4.2.7 on 2024-02-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='photo',
            new_name='image',
        ),
    ]
