# Generated by Django 4.2.7 on 2024-03-06 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_Notices', to=settings.AUTH_USER_MODEL, verbose_name='글쓴이'),
        ),
        migrations.AddField(
            model_name='notice',
            name='files',
            field=models.ManyToManyField(blank=True, to='notice.file', verbose_name='파일'),
        ),
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ManyToManyField(blank=True, to='notice.image', verbose_name='이미지'),
        ),
    ]
