# Generated by Django 4.2.7 on 2024-02-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_rename_photo_notice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='files',
            field=models.ManyToManyField(blank=True, to='notice.file', verbose_name='파일'),
        ),
    ]
