# Generated by Django 4.2.7 on 2024-04-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_alter_notice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='중요 여부'),
        ),
    ]
