# Generated by Django 4.2.7 on 2024-01-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=1, max_length=100, verbose_name='id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
    ]
