# Generated by Django 4.2.7 on 2024-01-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_updated_dt_user_user_id_alter_user_created_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=100, verbose_name='이름'),
            preserve_default=False,
        ),
    ]
