# Generated by Django 4.2.7 on 2024-01-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_user_id_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=300, verbose_name='비밀번호'),
        ),
    ]
