# Generated by Django 4.2.7 on 2024-02-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_users_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sns_id', models.CharField(max_length=255, unique=True)),
                ('sns_email', models.EmailField(max_length=254, unique=True)),
                ('sns_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'verbose_name': 'sns유저',
                'verbose_name_plural': 'sns유저',
            },
        ),
    ]
