# Generated by Django 4.2.7 on 2024-02-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
    ]
