# Generated by Django 4.2.7 on 2024-03-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.CharField(max_length=50, verbose_name='대표자')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('CRN', models.CharField(max_length=50, verbose_name='사업자등록번호')),
                ('depositor', models.CharField(max_length=50, verbose_name='예금주')),
                ('bank', models.CharField(max_length=50, verbose_name='입금은행')),
                ('account', models.CharField(max_length=50, verbose_name='계좌번호')),
            ],
            options={
                'verbose_name': '사업자 정보',
                'verbose_name_plural': '사업자 정보',
                'db_table': 'intro_BusinessInfo',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='주소1')),
                ('sub_address', models.CharField(max_length=100, verbose_name='주소2')),
                ('startTime', models.TimeField(verbose_name='시작시간')),
                ('endTime', models.TimeField(verbose_name='종료시간')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처1')),
                ('sub_phone', models.CharField(max_length=20, verbose_name='연락처2')),
            ],
            options={
                'verbose_name': '오시는 길',
                'verbose_name_plural': '오시는 길',
                'db_table': 'intro_Contact',
            },
        ),
    ]
