# Generated by Django 4.2.7 on 2024-03-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_businessinfo_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructors',
            name='created_at',
        ),
    ]
