# Generated by Django 4.2.7 on 2024-03-27 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0003_remove_instructors_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='startTime',
        ),
        migrations.AddField(
            model_name='contact',
            name='latitude',
            field=models.FloatField(default=35.2220973957462, verbose_name='지도 위도'),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.FloatField(default=128.676299239476, verbose_name='지도 경도'),
        ),
        migrations.AddField(
            model_name='contact',
            name='weekday_end_time',
            field=models.TimeField(default=datetime.time(19, 0), verbose_name='평일종료시간'),
        ),
        migrations.AddField(
            model_name='contact',
            name='weekday_start_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='평일시작시간'),
        ),
        migrations.AddField(
            model_name='contact',
            name='weekend_end_time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='주말종료시간'),
        ),
        migrations.AddField(
            model_name='contact',
            name='weekend_start_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='주말시작시간'),
        ),
    ]
