# Generated by Django 4.2.7 on 2024-03-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0004_remove_contact_endtime_remove_contact_starttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='map_add',
            field=models.CharField(default=2, max_length=100, verbose_name='지도 주소'),
            preserve_default=False,
        ),
    ]
