# Generated by Django 4.2.7 on 2024-03-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0005_contact_map_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='map_add',
            field=models.CharField(max_length=100, null=True, verbose_name='지도 주소'),
        ),
    ]
