# Generated by Django 4.2.7 on 2024-03-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0006_alter_contact_map_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='map_add',
            field=models.CharField(default='https://map.naver.com/p/entry/place/1605260808', max_length=100, verbose_name='지도 주소'),
        ),
    ]
