# Generated by Django 4.2.7 on 2023-12-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='강의명')),
                ('description', models.TextField(verbose_name='강의설명')),
                ('image', models.ImageField(null=True, upload_to='course', verbose_name='강의사진')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
            ],
            options={
                'verbose_name': '강의',
                'verbose_name_plural': '강의',
                'db_table': 'courseList',
            },
        ),
    ]
